# Generated by Django 2.0 on 2018-02-25 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_question'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='sub',
            new_name='subject',
        ),
    ]
